[package]
name = "rust-async-example"
version = "0.1.0"
authors = ["Yota Toyama <raviqqe@gmail.com>"]

[dependencies]
futures = { git = "https://github.com/rust-lang-nursery/futures-rs", branch = "0.3", features = ["nightly"] }
